version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development 
    container_name: news_api_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/uploads:/usr/src/app/uploads
    env_file:
      - ./backend/.env 
    depends_on:
      - mongo 
    networks:
      - news-network

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: news_api_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - news-network
    stdin_open: true 
    tty: true

  mongo:
    image: mongo:latest
    container_name: news_api_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    networks:
      - news-network

volumes:
  mongo-data:

networks:
  news-network:
    driver: bridge