version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development 
    container_name: news_api_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - ./.env 
    depends_on:
      - mongo 
    networks:
      - news-network

  mongo:
    image: mongo:latest
    container_name: news_api_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    networks:
      - news-network

volumes:
  mongo-data:

networks:
  news-network:
    driver: bridge